export const FETCH_STORY_START = 'FETCH_STORY_START';
export const FETCH_STORY_SUCCESS = 'FETCH_STORY_SUCCESS';
export const FETCH_STORY_FAIL = 'FETCH_STORY_FAIL ';
export const FETCH_ALL_STORIES_START = 'FETCH_ALL_STORIES_START';
export const FETCH_ALL_STORIES_SUCCESS = 'FETCH_ALL_STORIES_SUCCESS';
export const FETCH_ALL_STORIES_FAIL = 'FETCH_ALL_STORIES_FAIL ';